# Generated by Django 5.2.4 on 2025-09-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=350, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('normal', 'Normal Shipping (5-7 days) - Rs. 350'), ('express', 'Express Shipping (2-3 days) - Rs. 500')], default='normal', max_length=20),
        ),
    ]
